---
namespace: cisco
name: mso
# The version of the collection. Must be compatible with semantic versioning
version: 1.0.1
readme: README.md
authors:
- Dag Wieers (@dagwieers)
- Nirav Katarmal (@nkatarmal-crest)
- Lionel Hercot (@lhercot)
- Cindy Zhao (@cizhao)
- Shreyas Srish (@shrsr)
description: An Ansible collection for managing Cisco ACI Multi-Site
license_file: 'LICENSE'
tags: 
- cisco
- aci
- cloud
- collection
- networking
- sdn
- mso
- multisite
repository: https://github.com/CiscoDevNet/ansible-mso
documentation: https://docs.ansible.com/ansible/latest/scenario_guides/guide_aci.html
homepage: https://cisco.com/go/aci
issues: https://github.com/CiscoDevNet/ansible-mso/issues
