---
namespace: cisco
name: mso
# The version of the collection. Must be compatible with semantic versioning
version: 0.0.5
readme: README.md
authors:
- Dag Wieers (@dagwieers) <dag@wieers.com>
- Nirav Katarmal (@nkatarmal-crest) <nirav.katarmal@crestdatasys.com>
- Lionel Hercot (@lhercot) <lhercot@cisco.com>
description: An Ansible collection for managing Cisco ACI Multi-Site
license_file: 'LICENSE'
tags: 
- cisco
- aci
- cloud
- collection
- networking
- sdn
- mso
- multisite
repository: https://github.com/CiscoDevNet/ansible-mso
documentation: https://docs.ansible.com/ansible/latest/scenario_guides/guide_aci.html
homepage: https://cisco.com/go/aci
issues: https://github.com/CiscoDevNet/ansible-mso/issues